apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: keycloak
build:
  artifacts: []
#  - image: mytrack-srv
#    context: .
#    jib: {}
deploy:
  kubectl:
    manifests:
#    - kubernetes-manifests/mysql-pv.yaml
#    - kubernetes-manifests/mysql-deployment.yaml
    - kubernetes-manifests/keycloak-service.yaml
    #- kubernetes-manifests/keycloak-ingress.yaml
