apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 9999
      targetPort: 8080
  selector:
    app: keycloak
  type: LoadBalancer
  #externalIPs:
  #  - 192.168.0.108
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:11.0.2
          env:
            - name: DB_VENDOR
              value: mysql
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  name: mytrack-srv-secret
                  key: keycloak.user
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mytrack-srv-secret
                  key: keycloak.password
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: keycloak.dbuser
                  name: mytrack-srv-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: keycloak.dbpassword
                  name: mytrack-srv-secret
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080