apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql.rootpassword
                  name: mytrack-srv-secret
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: keycloak.dbuser
                  name: mytrack-srv-secret
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: keycloak.dbpassword
                  name: mytrack-srv-secret
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: keycloak.database
                  name: mytrack-srv-secret
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-config
              mountPath: /etc/mysql/conf.d/custom.cnf
              subPath: custom.cnf
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        - name: mysql-config
          configMap:
            name: mysql-config-file
