apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytrack-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mytrack-srv
  template:
    metadata:
      labels:
        app: mytrack-srv
    spec:
      containers:
      - name: mytrack-srv
        image: fondorg/mytrack-srv
        ports:
        - containerPort: 9090
        env:
        - name: PORT
          value: "9090"
        # This environment variable enables debugging support for the container.
        # Remove this to disable the debug build.
        - name: JAVA_TOOL_OPTIONS
          value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mytrack-srv-secret
              key: mysql.username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mytrack-srv-secret
              key: mysql.password
        - name: KEYCLOAK_RESOURCE
          valueFrom:
            secretKeyRef:
              name: mytrack-srv-secret
              key: keycloak.resource
        volumeMounts:
          - mountPath: /home/gradle/config
            name: mytrack-srv-config
      volumes:
        - name: mytrack-srv-config
          configMap:
            name: mytrack-srv-config-file

