apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytrack-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mytrack-srv
  template:
    metadata:
      labels:
        app: mytrack-srv
    spec:
      containers:
      - name: server
        image: mytrack-srv
        ports:
        - containerPort: 9090
        env:
        - name: PORT
          value: "9090"
        # This environment variable enables debugging support for the container.
        # Remove this to disable the debug build.
        - name: JAVA_TOOL_OPTIONS
          value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
